export interface PlaceData {
  id: string;
  name: string;
  region: string;
  emoji: string;
  color: string;
  desc: string;
  mapX: number;
  mapY: number;
  isIsland?: boolean;
  stats: { value: string; label: string }[];
  overview: { label: string; value: string }[];
  travel: { icon: string; name: string; detail: string }[];
  travelExtra: { label: string; value: string }[];
  food: { emoji: string; name: string; desc: string }[];
  hotels: { icon: string; name: string; detail: string; stars: string }[];
  coords: string;
  mapUrl: string;
}

export const PLACES: PlaceData[] = [
  {
    id: "chennai",
    name: "Chennai",
    region: "North Tamil Nadu · Coromandel Coast",
    emoji: "🏛️",
    color: "#8B2B06",
    mapX: 390, mapY: 62,
    desc: "Chennai, Tamil Nadu's capital, is a metropolis of 10 million that wears its history and modernity with equal ease. Marina Beach — the world's second longest urban beach at 13 km — frames the city on one side while the 400-year-old Fort St. George anchors its colonial past. The city is the global headquarters of Bharatanatyam, Carnatic music, and South Indian cinema.",
    stats: [
      { value: "10M+", label: "Population" },
      { value: "13 km", label: "Marina Beach" },
      { value: "2,300+", label: "Years Old" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "November – February (cool & dry)" },
      { label: "Known For", value: "Marina Beach · Kapaleeshwarar Temple · Fort St. George · Bharatanatyam · Filter Coffee" },
      { label: "Language", value: "Tamil (primary) · English widely spoken" },
      { label: "Airport", value: "Chennai International Airport (MAA) — 16 km from city centre" },
      { label: "City Transport", value: "Metro Rail (Phase 1 & 2) · MRTS · App cabs · Share autos" },
    ],
    travel: [
      { icon: "✈️", name: "By Air", detail: "Direct flights from all major Indian cities & international hubs (Dubai, Singapore, London)" },
      { icon: "🚂", name: "By Train", detail: "Chennai Central & Egmore — well connected to all TN districts and major Indian cities" },
      { icon: "🚌", name: "By Bus", detail: "Koyambedu CMBT (Asia's largest bus terminus) — coaches from Bengaluru, Hyderabad, Kerala" },
    ],
    travelExtra: [
      { label: "From Bengaluru", value: "6 hrs by bus · 5 hrs by train · 1 hr by flight" },
      { label: "From Madurai", value: "7–8 hrs by bus · 6–7 hrs by train · 1 hr by flight" },
    ],
    food: [
      { emoji: "🍚", name: "Chettinad Biryani", desc: "Aromatic rice with spiced meats & star anise" },
      { emoji: "🥞", name: "Kothu Parotta", desc: "Shredded flatbread with egg, masala & salna" },
      { emoji: "☕", name: "Filter Kaapi", desc: "Chicory-rich decoction with frothed milk, served in davara" },
      { emoji: "🫓", name: "Idli Sambar", desc: "Steamed rice cakes with lentil broth — the city's soul food" },
      { emoji: "🦀", name: "Pepper Crab", desc: "Marina-catch crab with Madras pepper masala" },
      { emoji: "🌶", name: "Chicken 65", desc: "Spicy deep-fried chicken — a Chennai invention from 1965" },
    ],
    hotels: [
      { icon: "👑", name: "The Leela Palace", detail: "5★ · Anna Salai · Luxury suites, spa, rooftop infinity pool", stars: "★★★★★" },
      { icon: "🏨", name: "ITC Grand Chola", detail: "5★ · Guindy · Largest hotel in South Asia, 600 rooms", stars: "★★★★★" },
      { icon: "🛎", name: "Taj Coromandel", detail: "5★ · Nungambakkam · Heritage property, iconic South Indian dining", stars: "★★★★★" },
      { icon: "🏩", name: "Hablis Hotel", detail: "4★ · Guindy · Modern, rooftop pool, business-friendly mid-range", stars: "★★★★" },
      { icon: "🏠", name: "Zostel Chennai", detail: "Budget · T Nagar · Backpacker favourite with social events", stars: "★★★" },
    ],
    coords: "13.0827° N, 80.2707° E",
    mapUrl: "https://maps.google.com/?q=Chennai,Tamil+Nadu",
  },
  {
    id: "mahabalipuram",
    name: "Mahabalipuram",
    region: "Coromandel Coast · 60 km S of Chennai",
    emoji: "🗿",
    color: "#2B4A6B",
    mapX: 383, mapY: 105,
    desc: "Mahabalipuram — Mamallapuram — was the Pallava dynasty's port city and artistic laboratory. UNESCO-protected rock-cut temples, monolithic rathas (chariots), and bas-reliefs hewn from boulders still stand metres from the Bay of Bengal. The Shore Temple at sunrise, silhouetted against the sea, is one of the defining images of Indian heritage.",
    stats: [
      { value: "7th C", label: "Pallava Era" },
      { value: "40+", label: "Rock Monuments" },
      { value: "UNESCO", label: "World Heritage" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "November – March (sea is calm, skies clear)" },
      { label: "Known For", value: "Shore Temple · Arjuna's Penance · Five Rathas · Pallava Sculpture School" },
      { label: "UNESCO", value: "Group of Monuments at Mahabalipuram — World Heritage Site (1984)" },
      { label: "Beach", value: "Mahabalipuram Beach · Silver Beach — safe for morning swims" },
      { label: "Airport", value: "Chennai International Airport (MAA) — 58 km north via ECR" },
    ],
    travel: [
      { icon: "🚌", name: "By Bus", detail: "TNSTC 118C from Chennai Koyambedu — 2 hrs, frequent departures" },
      { icon: "🚗", name: "By Road", detail: "East Coast Road (ECR) — scenic coastal drive, 90 min from Chennai" },
      { icon: "🛺", name: "Day Trip", detail: "Easily combined with Kanchipuram for a heritage circuit" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "90 min via ECR coastal route (60 km)" },
      { label: "Local Transport", value: "Bicycle rentals · Autos between monuments · Walking between sites" },
    ],
    food: [
      { emoji: "🦀", name: "Lobster & Crab", desc: "Fresh catch grilled with pepper — harbour-side beach shacks" },
      { emoji: "🐟", name: "Vanjaram Fry", desc: "King fish pan-fried in coastal spice paste" },
      { emoji: "🍤", name: "Prawn Masala", desc: "Bay of Bengal prawns in tomato-coriander sauce" },
      { emoji: "🥞", name: "Uthappam", desc: "Thick rice pancake topped with onions, tomatoes & ginger" },
      { emoji: "🍋", name: "Lemon Rice", desc: "Turmeric-kissed rice with curry leaves & roasted peanuts" },
      { emoji: "🥥", name: "Coconut Water", desc: "Straight from husk, sold beside every monument" },
    ],
    hotels: [
      { icon: "👑", name: "Radisson Blu Resort", detail: "5★ · Kovalam · Beach-front with infinity pool & spa", stars: "★★★★★" },
      { icon: "🏨", name: "GRT Temple Bay", detail: "4★ · Shore Temple Road · Pool, spa & heritage ambiance", stars: "★★★★" },
      { icon: "🛎", name: "Tara Fisher Hotel", detail: "4★ · Beachside boutique seafood resort facing sea", stars: "★★★★" },
      { icon: "🏩", name: "Hotel Mamalla Heritage", detail: "3★ · East Raja St · Central, popular with heritage tourists", stars: "★★★" },
      { icon: "🏠", name: "Blue Elephant Guesthouse", detail: "Budget · Quiet lane · Basic but charming & sociable", stars: "★★★" },
    ],
    coords: "12.6269° N, 80.1927° E",
    mapUrl: "https://maps.google.com/?q=Mahabalipuram,Tamil+Nadu",
  },
  {
    id: "kanchipuram",
    name: "Kanchipuram",
    region: "North Tamil Nadu · City of Thousand Temples",
    emoji: "🏵️",
    color: "#5A1A72",
    mapX: 335, mapY: 85,
    desc: "Kanchipuram is one of Hinduism's seven sacred cities — a living temple town where over 1,000 shrines span more than 2,000 years of continuous worship. It is equally celebrated for Kanchipuram silk sarees, hand-woven with real zari thread. The silk weavers' quarters bustle with looms while the towering gopurams cast long shadows over its ancient streets.",
    stats: [
      { value: "1,000+", label: "Temples" },
      { value: "2,000+", label: "Years Old" },
      { value: "Silk", label: "Capital of TN" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (festivals & cool weather)" },
      { label: "Known For", value: "Ekambareswarar Temple · Kamakshi Amman · Kailasanatha Temple · Silk sarees" },
      { label: "Religion", value: "One of Hinduism's Sapta Moksha Puri (seven liberation cities)" },
      { label: "Silk", value: "Kanchipuram sarees are GI-tagged — visit weavers directly at Pillayar Koil St" },
      { label: "Airport", value: "Chennai International Airport (MAA) — 75 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Kanchipuram Jn — EMU trains from Chennai every 30–60 min (90 min journey)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC buses every 15 min from Chennai Koyambedu (2 hrs)" },
      { icon: "🛺", name: "Day Trip", detail: "Perfect day-trip from Chennai; also combine with Mahabalipuram" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "75 km · 2 hrs by bus · 90 min by EMU train" },
      { label: "Local Transport", value: "Cycle rickshaws & autos between temples · Walking in old town" },
    ],
    food: [
      { emoji: "🥛", name: "Paal Payasam", desc: "Slow-cooked sweet rice pudding with cardamom" },
      { emoji: "🍚", name: "Ven Pongal", desc: "Rice & moong dal with ghee, pepper & cumin" },
      { emoji: "🥞", name: "Ghee Roast Dosa", desc: "Crispy dosa smeared with clarified butter" },
      { emoji: "🥣", name: "Kozhukattai", desc: "Steamed rice flour dumplings, sweet & savoury" },
      { emoji: "☕", name: "Filter Coffee", desc: "Temple-town style — served strong at every stall" },
      { emoji: "🌿", name: "Kootu", desc: "Seasonal vegetable & lentil stew with coconut" },
    ],
    hotels: [
      { icon: "🏨", name: "Baboo Soorya Hotel", detail: "3★ · Gandhi Rd · Clean, central, temple-facing rooms", stars: "★★★" },
      { icon: "🛎", name: "Hotel Saradharam", detail: "3★ · Near Kamakshi Temple · Heritage feel, restaurant", stars: "★★★" },
      { icon: "🏩", name: "GK Guest House", detail: "Budget · Silk weavers' quarter · Homely atmosphere", stars: "★★" },
      { icon: "🏠", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Reliable; walking distance to main temples", stars: "★★" },
      { icon: "🌿", name: "Day-Trip Base", detail: "Most visitors stay in Chennai & take a day trip to Kanchipuram", stars: "—" },
    ],
    coords: "12.8342° N, 79.7036° E",
    mapUrl: "https://maps.google.com/?q=Kanchipuram,Tamil+Nadu",
  },
  {
    id: "vellore",
    name: "Vellore",
    region: "North Tamil Nadu · Fort City",
    emoji: "🏰",
    color: "#3D1A5C",
    mapX: 281, mapY: 77,
    desc: "Vellore commands attention with its 16th-century granite fort — one of India's finest examples of military architecture — that still stands intact with a moat filled by the Palar river. Inside the fort, the Jalakanteswarar Temple is a gem of Vijayanagara craftsmanship. Nearby, the golden-roofed Sripuram temple complex glitters across 40 acres of star-shaped walkways.",
    stats: [
      { value: "16th C", label: "Fort Built" },
      { value: "40 acres", label: "Sripuram" },
      { value: "CMC", label: "Asia's Best Hospital" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – February (pleasant & dry)" },
      { label: "Known For", value: "Vellore Fort · Sripuram Golden Temple · Jalakanteswarar Temple · CMC Hospital" },
      { label: "Golden Temple", value: "Sripuram Sri Lakshmi Narayani — covered with 1,500 kg of pure gold" },
      { label: "Medical Hub", value: "CMC (Christian Medical College) — ranked Asia's best hospital" },
      { label: "Airport", value: "Chennai International Airport (MAA) — 145 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Katpadi Junction (8 km away) — well-connected to Chennai (1.5 hrs) & Bangalore (3 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "Frequent buses from Chennai (2.5 hrs), Bangalore (3 hrs), Tirupati (1.5 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-48 from Chennai (145 km · 2.5 hrs) · NH-40 from Bangalore (215 km · 3 hrs)" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "145 km · 2.5 hrs by road or bus · 1.5 hrs by train" },
      { label: "From Bangalore", value: "215 km · 3 hrs by road · 3 hrs by train via Katpadi" },
    ],
    food: [
      { emoji: "🍗", name: "Military Hotel Chicken", desc: "Vellore's iconic no-frills chicken curry with parotta" },
      { emoji: "🥞", name: "Pesarattu", desc: "Green moong dosa — popular from Andhra influence" },
      { emoji: "🍳", name: "Egg Kothu Parotta", desc: "Shredded parotta with egg & spices on iron griddle" },
      { emoji: "☕", name: "Irani Chai", desc: "Thick sweet tea from the fort-area chai stalls" },
      { emoji: "🫙", name: "Murukku", desc: "Crispy rice flour spirals — popular street snack" },
      { emoji: "🥘", name: "Mutton Kuzhambu", desc: "Slow-cooked mutton in black pepper & tamarind gravy" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Prince Manor", detail: "4★ · Long Bazaar · Largest hotel in Vellore, pool & dining", stars: "★★★★" },
      { icon: "🛎", name: "Darling Residency", detail: "3★ · Near CMC · Business & medical visitor favourite", stars: "★★★" },
      { icon: "🏩", name: "Hotel Mayflower", detail: "3★ · Anna Salai · Central, clean, restaurant on-site", stars: "★★★" },
      { icon: "🏠", name: "Hotel Vel Murugan", detail: "Budget · Near fort · Basic rooms, good local food nearby", stars: "★★" },
      { icon: "🌿", name: "Sripuram Guest House", detail: "Budget · Inside temple complex · Pilgrim-dedicated stays", stars: "★★" },
    ],
    coords: "12.9202° N, 79.1333° E",
    mapUrl: "https://maps.google.com/?q=Vellore,Tamil+Nadu",
  },
  {
    id: "tiruvannamalai",
    name: "Tiruvannamalai",
    region: "North Tamil Nadu · Sacred Fire Hill",
    emoji: "🔥",
    color: "#8B3D00",
    mapX: 276, mapY: 141,
    desc: "Tiruvannamalai is built around Arunachala — a sacred hill believed by Shaivites to be Lord Shiva himself, the element of fire made mountain. The Arunachaleswarar Temple at its base is one of the five Panchabhutha Lingas, representing fire. Each Karthigai Deepam full moon, a massive beacon is lit on the hill's summit, visible for miles across the plains.",
    stats: [
      { value: "2,669m", label: "Arunachala Circuit" },
      { value: "Karthigai", label: "Major Festival" },
      { value: "Ramana", label: "Maharshi Ashram" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March; Karthigai Deepam festival (Nov/Dec) draws 3 million pilgrims" },
      { label: "Known For", value: "Arunachaleswarar Temple · Arunachala Girivalam (14km circuit) · Sri Ramana Ashram" },
      { label: "Spirituality", value: "Sri Ramana Maharshi's life ashram; major Advaita pilgrimage site" },
      { label: "Girivalam", value: "Barefoot circumambulation of Arunachala hill — 14 km, done every full moon" },
      { label: "Airport", value: "Chennai Airport (MAA) — 185 km · Bangalore Airport — 225 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Tiruvannamalai station — trains from Villupuram (1.5 hrs) & Chennai (3.5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "Direct buses from Chennai (4 hrs), Bangalore (5 hrs), Pondicherry (2.5 hrs)" },
      { icon: "🚗", name: "By Road", detail: "Via NH-66 from Chennai (185 km · 3.5 hrs); scenic route via Gingee" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "185 km · 4 hrs by bus or 3.5 hrs by road" },
      { label: "From Pondicherry", value: "100 km · 2.5 hrs; popular spiritual circuit combination" },
    ],
    food: [
      { emoji: "🍚", name: "Ashram Meals", desc: "Simple sattvic meal at Sri Ramana Ashram dining hall" },
      { emoji: "🥣", name: "Pongal & Chutney", desc: "Temple prasad — rice with lentils and coconut chutney" },
      { emoji: "🫕", name: "Kadala Curry", desc: "Black chickpea curry with parotta — pilgrims' staple" },
      { emoji: "🌿", name: "Panneer Soda", desc: "Rose syrup soda — ubiquitous street drink during festival" },
      { emoji: "☕", name: "Gingee Coffee", desc: "Strong filter coffee from roadside shops near hill" },
      { emoji: "🍌", name: "Banana Jaggery Sweet", desc: "Ripe banana mashed with jaggery — temple offering" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Arunachala", detail: "3★ · Girivalam Rd · Hill views, rooftop restaurant", stars: "★★★" },
      { icon: "🛎", name: "Adi Annamalai Hotel", detail: "3★ · Near temple · Vegetarian hotel, darshan package", stars: "★★★" },
      { icon: "🏩", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Hill-facing rooms at affordable rates", stars: "★★" },
      { icon: "🏠", name: "Ramana Ashram Guest House", detail: "Ashram · Donation basis · Spiritual seekers only", stars: "🙏" },
      { icon: "🌿", name: "Sesshadri Ashram", detail: "Ashram · Simple rooms · For meditation & quiet stays", stars: "🙏" },
    ],
    coords: "12.2253° N, 79.0747° E",
    mapUrl: "https://maps.google.com/?q=Tiruvannamalai,Tamil+Nadu",
  },
  {
    id: "pondicherry",
    name: "Pondicherry",
    region: "Union Territory · French Riviera of the East",
    emoji: "🌊",
    color: "#1A3D5C",
    mapX: 349, mapY: 169,
    desc: "Pondicherry is India's most improbable city — where Tamil and French cultures have coexisted for 300 years. The White Town's grid of bougainvillea-draped colonial boulevards, mustard-yellow buildings, and a seafront promenade feel transplanted from the Côte d'Azur. Twelve kilometres inland, Auroville — the futuristic universal township — draws seekers from 50 nations.",
    stats: [
      { value: "300 yrs", label: "French Legacy" },
      { value: "Auroville", label: "International Township" },
      { value: "12 km", label: "Promenade" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (clear seas, ideal promenade weather)" },
      { label: "Known For", value: "French Quarter · Promenade Beach · Auroville · Sri Aurobindo Ashram" },
      { label: "Unique Feature", value: "Only place in India where French is an official language alongside Tamil" },
      { label: "Auroville", value: "A utopian international township — 50 nations, 3,000 residents, no money inside" },
      { label: "Airport", value: "Chennai Airport (MAA) — 150 km; Pondicherry has a small domestic airstrip" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Pondicherry station — Puducherry Express from Chennai (3.5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC every 30 min from Chennai (3.5 hrs) · From Madurai (6 hrs)" },
      { icon: "🚗", name: "By Road", detail: "ECR from Chennai (150 km · 3 hrs) — scenic coastal drive highly recommended" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "150 km · 3 hrs via ECR; 3.5 hrs by Puducherry Express" },
      { label: "Local Transport", value: "Cycling through White Town · Auto-rickshaws · Scooter rentals" },
    ],
    food: [
      { emoji: "🥐", name: "French Bakery Croissant", desc: "Freshly baked at Café des Arts or Baker Street" },
      { emoji: "🦞", name: "Grilled Lobster", desc: "Seafood bistros on Goubert Promenade — catch of the day" },
      { emoji: "🍛", name: "Pondi Curry Meal", desc: "Tamil banana-leaf meal with French-influenced sides" },
      { emoji: "🍷", name: "Pondicherry Wine", desc: "India's oldest winery — Grover Zampa made near Pondicherry" },
      { emoji: "☕", name: "Café au Lait", desc: "French-press coffee at promenade cafes with a Pondi sunrise" },
      { emoji: "🥘", name: "Kothu Parotta", desc: "Tamil street staple — shredded flatbread with egg & spices" },
    ],
    hotels: [
      { icon: "👑", name: "Le Dupleix", detail: "Heritage · 5★ · Dumas St · Colonial French mansion, period furniture", stars: "★★★★★" },
      { icon: "🏨", name: "The Promenade Hotel", detail: "4★ · Beach Rd · Sea-facing rooms, rooftop cocktail bar", stars: "★★★★" },
      { icon: "🛎", name: "Palais de Mahé", detail: "4★ · French Quarter · Boutique colonial, curated décor", stars: "★★★★" },
      { icon: "🏩", name: "Kailash Nivas", detail: "3★ · White Town lane · Heritage guesthouse, courtyard garden", stars: "★★★" },
      { icon: "🏠", name: "Zostel Pondicherry", detail: "Budget · Near beach · Sociable hostel with daily activities", stars: "★★★" },
    ],
    coords: "11.9416° N, 79.8083° E",
    mapUrl: "https://maps.google.com/?q=Pondicherry,India",
  },
  {
    id: "chidambaram",
    name: "Chidambaram",
    region: "Cauvery Delta · Temple of Cosmic Dance",
    emoji: "💃",
    color: "#5C2A00",
    mapX: 338, mapY: 218,
    desc: "Chidambaram is home to the Nataraja Temple — arguably the most philosophically significant temple in all of Hinduism. Here Shiva is worshipped as Nataraja, Lord of Cosmic Dance, eternally performing the Ananda Tandava. The famous 'Chidambara Rahasyam' (the Divine Secret) is revealed in a curtained sanctum — a void, the Akasha Lingam — representing the infinite.",
    stats: [
      { value: "10th C", label: "Temple Era" },
      { value: "Akasha", label: "Space Element" },
      { value: "Nataraja", label: "Cosmic Dance" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "November – February; Natyanjali Dance Festival (February) is extraordinary" },
      { label: "Known For", value: "Thillai Nataraja Temple · Chidambaram Rahasyam · Nataraja bronze sculpture origin" },
      { label: "Architecture", value: "Four gopurams covered in 108 Bharatanatyam poses from Natya Shastra" },
      { label: "Festival", value: "Natyanjali — classical dancers perform at the temple for 5 days every February" },
      { label: "Airport", value: "Trichy Airport (TRZ) — 160 km; Chennai Airport — 220 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Chidambaram station — trains from Chennai (3.5 hrs) and Villupuram (1 hr)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Chennai (5 hrs), Trichy (3 hrs), Pondicherry (2 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-32 from Pondicherry (65 km · 1.5 hrs); NH-32 from Trichy (160 km)" },
    ],
    travelExtra: [
      { label: "From Pondicherry", value: "65 km · 1.5 hrs — excellent combination day trip" },
      { label: "From Chennai", value: "220 km · 5 hrs by road; 3.5 hrs by direct train" },
    ],
    food: [
      { emoji: "🍚", name: "Chidambaram Vilaiyaadu Sappadu", desc: "Banana leaf feast — 12+ items for temple festivals" },
      { emoji: "🥘", name: "Poricha Kootu", desc: "Seasonal gourds cooked with coconut & spices" },
      { emoji: "🥣", name: "Sakkarai Pongal", desc: "Sweet rice pudding with jaggery — temple prasad" },
      { emoji: "🍌", name: "Kadalai Maavu Halwa", desc: "Bengal gram flour sweet with saffron & ghee" },
      { emoji: "🥞", name: "Appam", desc: "Bowl-shaped fermented rice crêpe — a Cauvery delta staple" },
      { emoji: "☕", name: "Ilaneer Kaapi", desc: "Filter coffee blended with fresh tender coconut water" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Saradharam", detail: "3★ · Car St · Temple-view rooms, vegetarian restaurant", stars: "★★★" },
      { icon: "🛎", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Centrally located, reliable service", stars: "★★★" },
      { icon: "🏩", name: "Hotel Akshaya", detail: "2★ · Near temple · Budget pilgrim hotel, clean rooms", stars: "★★" },
      { icon: "🏠", name: "Akshaya Ashram", detail: "Ashram stays · Donation · For spiritual visitors", stars: "🙏" },
      { icon: "🌿", name: "Pichavaram Day Trip", detail: "Stay in Pondicherry & combine with Pichavaram mangroves", stars: "—" },
    ],
    coords: "11.3992° N, 79.6912° E",
    mapUrl: "https://maps.google.com/?q=Chidambaram,Tamil+Nadu",
  },
  {
    id: "salem",
    name: "Salem",
    region: "Central Tamil Nadu · Steel City",
    emoji: "⛰️",
    color: "#3D5C1A",
    mapX: 192, mapY: 193,
    desc: "Salem is the steel and turmeric capital of Tamil Nadu — a major industrial and commercial city flanked by the Shevaroy Hills. Just 28 km uphill lies Yercaud, a serene hill station of coffee estates, orange orchards, and fragrant eucalyptus, accessible on a winding ghat road. Salem's old bazaars trade in everything from mangoes to Salem steel.",
    stats: [
      { value: "1,500m", label: "Yercaud Altitude" },
      { value: "Steel", label: "Salem Steel Plant" },
      { value: "28 km", label: "To Yercaud" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – June (Yercaud best in summer April–June)" },
      { label: "Known For", value: "Yercaud Hill Station · Salem Steel Plant · Sugarcane & turmeric trade · Killiyur Falls" },
      { label: "Yercaud", value: "Salem's hill station — Lady's Seat viewpoint, Yercaud Lake, coffee estates" },
      { label: "Local Pride", value: "Salem mangoes (Banganapalli & Malgoba) are famous across South India" },
      { label: "Airport", value: "Trichy Airport (TRZ) — 120 km; Coimbatore (CBE) — 150 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Salem Junction — major railway hub; trains from Chennai (4 hrs), Bangalore (4 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "Frequent TNSTC buses from Chennai (5 hrs), Coimbatore (3 hrs), Trichy (3 hrs)" },
      { icon: "⛰️", name: "To Yercaud", detail: "Shared buses from Salem New Bus Stand every 30 min (1.5 hrs up ghat road)" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "340 km · 5 hrs by road · 4 hrs by express train" },
      { label: "Salem → Yercaud", value: "28 km · 1.5 hrs by ghat road bus (7 hairpin bends!)" },
    ],
    food: [
      { emoji: "🥭", name: "Salem Mango Lassi", desc: "Malgoba & Banganapalli mango blended with curd" },
      { emoji: "🥘", name: "Kari Kuzhambu", desc: "Salem-style lamb curry with freshly ground masala" },
      { emoji: "🫕", name: "Keera Kootu", desc: "Greens cooked with lentils & grated coconut" },
      { emoji: "☕", name: "Yercaud Coffee", desc: "Estate-grown arabica — try at hill-station cafes" },
      { emoji: "🟠", name: "Yercaud Orange", desc: "Hill-grown Coorg oranges — sweet & slightly tart" },
      { emoji: "🥞", name: "Ragi Mudde", desc: "Finger millet balls with spiced mutton soup" },
    ],
    hotels: [
      { icon: "👑", name: "GRT Regency Salem", detail: "4★ · Fort Rd · Business hotel, pool, multi-cuisine", stars: "★★★★" },
      { icon: "🏨", name: "Hotel Sterling Yercaud", detail: "4★ · Yercaud · Estate-set cottages with hill views", stars: "★★★★" },
      { icon: "🛎", name: "Hotel Salem Castle", detail: "3★ · Central Salem · Near bus stand & railway station", stars: "★★★" },
      { icon: "🏩", name: "Tamilnadu Hotel Yercaud (TTDC)", detail: "Govt · Budget · Lake-view rooms in Yercaud", stars: "★★★" },
      { icon: "🏠", name: "Shevaroy Hills Resort", detail: "Budget · Yercaud · Family bungalow with garden & fireplace", stars: "★★★" },
    ],
    coords: "11.6643° N, 78.1460° E",
    mapUrl: "https://maps.google.com/?q=Salem,Tamil+Nadu",
  },
  {
    id: "ooty",
    name: "Ooty",
    region: "Nilgiri Hills · 2,240 m Altitude",
    emoji: "🌿",
    color: "#1A5C1A",
    mapX: 72, mapY: 217,
    desc: "Udhagamandalam — Ooty — sits atop the Nilgiri plateau where British colonists built bungalows to escape the heat. Today it lures visitors with rows of emerald tea gardens, conifer avenues, a century-old mountain railway that UNESCO has declared a World Heritage Site, and a crispness in the air rare anywhere in peninsular India.",
    stats: [
      { value: "2,240m", label: "Altitude" },
      { value: "1908", label: "Toy Train Year" },
      { value: "UNESCO", label: "Nilgiri Railway" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "April – June and Sep – Nov (avoid monsoon Jul–Aug; winter Dec–Jan for fog)" },
      { label: "Known For", value: "Nilgiri Mountain Railway · Botanical Garden · Doddabetta Peak · Tea Estates" },
      { label: "UNESCO", value: "Nilgiri Mountain Railway — World Heritage Site (2005)" },
      { label: "Wildlife", value: "Mudumalai Tiger Reserve · Bandipur National Park — both within 90 min" },
      { label: "Airport", value: "Coimbatore Airport (CBE) — 88 km · 3 hrs by ghat road" },
    ],
    travel: [
      { icon: "🚂", name: "Toy Train (UNESCO)", detail: "Mettupalayam → Ooty · 5 hrs of mountain views · Book months ahead" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Coimbatore (3 hrs) · KSRTC from Bengaluru (7 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-181 via Coimbatore — 36 hairpin bends on Kallar ghat; stunning drive" },
    ],
    travelExtra: [
      { label: "From Coimbatore", value: "88 km · 3 hrs by road · 5 hrs by heritage toy train" },
      { label: "Local Transport", value: "Taxis · Horse rides near lake · Cycling in town" },
    ],
    food: [
      { emoji: "☕", name: "Nilgiri Tea", desc: "Single-estate orthodox black tea — famously brisk & aromatic" },
      { emoji: "🍫", name: "Home-made Chocolate", desc: "Ooty's famous handmade fudge sold on every corner" },
      { emoji: "🥕", name: "Varkey Bread", desc: "Flaky layered bread eaten with hill butter & jam" },
      { emoji: "🥩", name: "Nilgiri Lamb Curry", desc: "Coconut & green herb curry — signature dish of the hills" },
      { emoji: "🍳", name: "Egg Hoppers", desc: "Bowl-shaped crêpe with egg — Sri Lankan-influenced" },
      { emoji: "🥦", name: "Hill Veggie Platter", desc: "Seasonal mountain vegetables: kohlrabi, turnip & carrot" },
    ],
    hotels: [
      { icon: "👑", name: "Savoy Hotel (Taj)", detail: "5★ · Sylks Road · 1829 colonial bungalow set in pine gardens", stars: "★★★★★" },
      { icon: "🏨", name: "Sterling Fern Hill", detail: "4★ · Fern Hill · Victorian palatial estate, butler service", stars: "★★★★" },
      { icon: "🛎", name: "Sinclairs Retreat Ooty", detail: "4★ · Ettines Rd · Hillside property, fireplace rooms", stars: "★★★★" },
      { icon: "🏩", name: "Hotel Lakeview", detail: "3★ · Lake area · Views of Ooty Lake; good value", stars: "★★★" },
      { icon: "🏠", name: "Reflections Guest House", detail: "Budget · Near Lake · Homely, run by a local Ooty family", stars: "★★★" },
    ],
    coords: "11.4102° N, 76.6950° E",
    mapUrl: "https://maps.google.com/?q=Ooty,Tamil+Nadu",
  },
  {
    id: "coimbatore",
    name: "Coimbatore",
    region: "Western TN · Gateway to Nilgiris",
    emoji: "🏭",
    color: "#2B4A1A",
    mapX: 80, mapY: 252,
    desc: "Known as the 'Manchester of South India', Coimbatore is Tamil Nadu's industrial powerhouse — producing over half the nation's pump sets and a major share of textiles. Flanked by the Western Ghats, it is the launching pad for Ooty, Valparai, and the Isha Yoga Centre, making it a remarkable blend of industry, nature, and spirituality.",
    stats: [
      { value: "3M+", label: "Population" },
      { value: "#1", label: "S.India Textiles" },
      { value: "Isha", label: "Yoga Centre" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March · Mild climate year-round due to Nilgiri influence" },
      { label: "Known For", value: "Isha Yoga Centre · Marudamalai Temple · Kovai Kutralam · Dhyanalinga" },
      { label: "Day Trips", value: "Ooty (88 km) · Valparai (100 km) · Pollachi · Anamalai Tiger Reserve" },
      { label: "Isha", value: "Isha Yoga Centre — 150-acre campus with Dhyanalinga, a consecrated yogic space" },
      { label: "Airport", value: "Coimbatore International Airport (CBE) — 11 km from city centre" },
    ],
    travel: [
      { icon: "✈️", name: "By Air", detail: "International flights to Dubai, Singapore; domestic to all Indian metros daily" },
      { icon: "🚂", name: "By Train", detail: "Coimbatore Jn — Shatabdi from Chennai (5h 45m), trains from Bangalore (5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC & KSRTC — frequent buses from Bengaluru (5 hrs), Chennai (8 hrs), Ooty" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "500 km · 5h 45m by Shatabdi · 8 hrs by bus · 1 hr by flight" },
      { label: "Local Transport", value: "SETC city buses · App cabs · Share autos · Hired cars for day trips" },
    ],
    food: [
      { emoji: "🍳", name: "Seeraga Samba Biryani", desc: "Tiny-grain rice biryani — Coimbatore's signature street dish" },
      { emoji: "☕", name: "Kovai Kaapi", desc: "Strong filter coffee, frothy, served West TN style in tumbler" },
      { emoji: "🥘", name: "Kuzhi Paniyaram", desc: "Ball-shaped rice & lentil dumplings with three chutneys" },
      { emoji: "🫕", name: "Murungai Keerai Curry", desc: "Drumstick leaf lentil curry with jaggery — rustic & hearty" },
      { emoji: "🥦", name: "Vazhakkai Fry", desc: "Raw plantain chips fried in coconut oil with chilli" },
      { emoji: "🍡", name: "Aval Payasam", desc: "Flattened rice pudding with cardamom, cashews & raisins" },
    ],
    hotels: [
      { icon: "👑", name: "Vivanta Coimbatore (Taj)", detail: "5★ · Avinashi Rd · Rooftop pool, multiple dining options", stars: "★★★★★" },
      { icon: "🏨", name: "The Residency Towers", detail: "4★ · Avinashi Rd · Business-class comfort, city views", stars: "★★★★" },
      { icon: "🛎", name: "Hotel KG Inn", detail: "3★ · RS Puram · Central, good value, popular with families", stars: "★★★" },
      { icon: "🏩", name: "Hotel Arcadia", detail: "2★ · Cross Cut Rd · Clean budget rooms near railway station", stars: "★★" },
      { icon: "🏠", name: "Zostel Coimbatore", detail: "Budget · Gandhipuram · Hostel with Nilgiri trip meetup group", stars: "★★★" },
    ],
    coords: "11.0168° N, 76.9558° E",
    mapUrl: "https://maps.google.com/?q=Coimbatore,Tamil+Nadu",
  },
  {
    id: "trichy",
    name: "Trichy",
    region: "Central TN · Rock Fort & River Delta",
    emoji: "🪨",
    color: "#5C3A1A",
    mapX: 242, mapY: 271,
    desc: "Tiruchirappalli rises dramatically from the flat Cauvery plains around a 83-metre granite outcrop — the Rock Fort — atop which perches the Ucchi Pillaiyar temple. Eight kilometres away on Srirangam Island sits the Ranganathaswamy Temple — the largest functioning Hindu temple in the world — with 21 gopurams, 49 shrines, and 7 concentric boundary walls enclosing an entire temple town.",
    stats: [
      { value: "83m", label: "Rock Fort Height" },
      { value: "World's Largest", label: "Functioning Temple" },
      { value: "21", label: "Gopurams (Srirangam)" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (comfortable heat; Vaikunta Ekadasi festival in Dec)" },
      { label: "Known For", value: "Rock Fort Temple · Srirangam Ranganathaswamy · Cauvery River · St. Lourdes Church" },
      { label: "UNESCO Nearby", value: "Great Living Chola Temples — Gangaikonda Cholapuram (70 km)" },
      { label: "Airport", value: "Trichy International Airport (TRZ) — 7 km from city centre" },
      { label: "Rail Hub", value: "Tiruchirappalli Junction — major rail hub connecting north & south TN" },
    ],
    travel: [
      { icon: "✈️", name: "By Air", detail: "TRZ airport — flights to Chennai, Bangalore, Delhi, Colombo, Singapore" },
      { icon: "🚂", name: "By Train", detail: "Tiruchirappalli Junction — Rock Fort Express from Chennai (5.5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "Frequent TNSTC from Chennai (6 hrs), Madurai (2 hrs), Coimbatore (4 hrs)" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "330 km · 6 hrs by bus · 5.5 hrs by train · 1 hr by flight" },
      { label: "Local Transport", value: "Autos & city buses · Share autos to Srirangam (8 km)" },
    ],
    food: [
      { emoji: "🍚", name: "Srirangam Kool", desc: "Fermented rice porridge served to Srirangam pilgrims" },
      { emoji: "🥘", name: "Mutton Sukka", desc: "Dry-fried mutton with freshly ground masala & curry leaves" },
      { emoji: "🥣", name: "Kavuni Arisi Payasam", desc: "Black rice pudding with cardamom — ancient Chola dessert" },
      { emoji: "🫓", name: "Wheat Parotta", desc: "Layered flatbread — Trichy's answer to the Chennai parotta" },
      { emoji: "☕", name: "Kumbakonam Degree Coffee", desc: "Authentic degree coffee from nearby Kumbakonam" },
      { emoji: "🌶", name: "Chettinad Chicken Chetna", desc: "Chettinad-spiced chicken from old-quarter restaurants" },
    ],
    hotels: [
      { icon: "👑", name: "GRT Grand Hotel", detail: "4★ · Williams Rd · Pool, spa, largest in Trichy", stars: "★★★★" },
      { icon: "🏨", name: "Hotel Sangam Trichy", detail: "4★ · Collector's Office Rd · River views, rooftop dining", stars: "★★★★" },
      { icon: "🛎", name: "Le Royal Park Hotel", detail: "3★ · McDonald's Rd · Modern, near Rock Fort", stars: "★★★" },
      { icon: "🏩", name: "Femina Hotel", detail: "3★ · Williams Rd · Old-school Trichy staple, reliable rooms", stars: "★★★" },
      { icon: "🏠", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Near Central Bus Stand, good location", stars: "★★" },
    ],
    coords: "10.7905° N, 78.7047° E",
    mapUrl: "https://maps.google.com/?q=Trichy,Tamil+Nadu",
  },
  {
    id: "kumbakonam",
    name: "Kumbakonam",
    region: "Cauvery Delta · Temple Town",
    emoji: "🏺",
    color: "#5C2A00",
    mapX: 310, mapY: 255,
    desc: "Kumbakonam lies in the fertile Cauvery Delta — a city of 188 temples in just 4 km radius. Famous for the Mahamaham festival that draws millions every 12 years to bathe in the sacred Mahamaham tank, it is also the origin of Kumbakonam Degree Coffee — India's most iconic strong coffee — and is surrounded by the finest bronze workshops continuing the Chola tradition.",
    stats: [
      { value: "188", label: "Temples in Town" },
      { value: "Every 12 Yrs", label: "Mahamaham Festival" },
      { value: "#1 Coffee", label: "Degree Coffee Origin" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March; Mahamaham year (next: 2028) is extraordinary" },
      { label: "Known For", value: "Adi Kumbeswarar Temple · Sarangapani Temple · Brihadeeswarar proximity · Degree Coffee" },
      { label: "Coffee", value: "Kumbakonam is the birthplace of 'Degree Coffee' — tested with a lactometer for purity" },
      { label: "Temples", value: "Sapta Stanam — 7 Shiva temples in a sacred circumambulation route" },
      { label: "Airport", value: "Trichy Airport (TRZ) — 60 km; Thanjavur (nearby) has no airport" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Kumbakonam station — trains from Chennai (6.5 hrs), Trichy (1.5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Chennai (7 hrs), Trichy (2 hrs), Thanjavur (1 hr)" },
      { icon: "🚗", name: "By Road", detail: "NH-83 from Trichy (96 km); easy temple circuit with Thanjavur (35 km away)" },
    ],
    travelExtra: [
      { label: "From Thanjavur", value: "35 km · 45 min — ideal same-day combination" },
      { label: "Local Transport", value: "Cycle rickshaws ideal · Auto-rickshaws to outlying temples" },
    ],
    food: [
      { emoji: "☕", name: "Kumbakonam Degree Coffee", desc: "The gold standard of filter coffee — chicory-rich, lactometer-tested purity" },
      { emoji: "🥞", name: "Idli with Hotel Sambar", desc: "Kumbakonam's sambar is temple-standard — tamarind-sweet & aromatic" },
      { emoji: "🍯", name: "Sakkara Pongal", desc: "Temple sweet pongal with jaggery & cashews" },
      { emoji: "🥮", name: "Paal Kozhukattai", desc: "Rice dumplings in cardamom coconut milk" },
      { emoji: "🫙", name: "Kavuni Arisi", desc: "Black rice pudding — ancient dessert of the Chola delta" },
      { emoji: "🍋", name: "Rasam Rice", desc: "Hot pepper & tamarind broth over rice — a complete meal" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Raya's", detail: "3★ · Near Mahamaham Tank · Trusted heritage hotel, vegetarian", stars: "★★★" },
      { icon: "🛎", name: "ARR Grand Hotel", detail: "3★ · TSR Big St · Clean, central, AC rooms with restaurant", stars: "★★★" },
      { icon: "🏩", name: "Hotel Athithi", detail: "2★ · Near bus stand · Budget, popular with pilgrims", stars: "★★" },
      { icon: "🏠", name: "Hotel Parikh", detail: "Budget · Head Post Office Rd · Simple rooms, good meals", stars: "★★" },
      { icon: "🌿", name: "Day-Trip Option", detail: "Most visitors stay in Thanjavur (35 km) or Trichy (96 km)", stars: "—" },
    ],
    coords: "10.9602° N, 79.3845° E",
    mapUrl: "https://maps.google.com/?q=Kumbakonam,Tamil+Nadu",
  },
  {
    id: "thanjavur",
    name: "Thanjavur",
    region: "Cauvery Delta · Chola Heartland",
    emoji: "🏯",
    color: "#5C3D00",
    mapX: 284, mapY: 274,
    desc: "Thanjavur was the capital of the mighty Chola empire, and its legacy endures in bronze — the finest Nataraja statues ever cast emerged from ateliers here. The Brihadeeswarar Temple, built by Raja Raja Chola I in 1010 CE, soars 66 metres, its tower cut from a single 80-tonne granite block, and remains an architectural wonder after a thousand years.",
    stats: [
      { value: "1010 CE", label: "Temple Built" },
      { value: "66m", label: "Vimana Height" },
      { value: "UNESCO", label: "World Heritage" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – February (Pongal festival in January is special)" },
      { label: "Known For", value: "Brihadeeswarar Temple · Chola Bronze Museum · Tanjore Painting · Saraswati Mahal Library" },
      { label: "UNESCO", value: "Great Living Chola Temples — World Heritage Site (includes Gangaikonda Cholapuram)" },
      { label: "Art Forms", value: "Tanjore paintings · Bharatanatyam · Veena instrument craftsmanship" },
      { label: "Airport", value: "Tiruchirappalli Airport (TRZ) — 60 km from Thanjavur" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Thanjavur Jn — Cholan Express from Chennai (6.5 hrs); Trichy (1 hr)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Chennai (7 hrs every hr), Trichy (1.5 hrs), Madurai (3 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-83 from Trichy (60 km · 1 hr); smooth 4-lane highway" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "350 km · 7 hrs by road · 6.5 hrs by Cholan Express" },
      { label: "Local Transport", value: "Cycle rickshaws ideal for the temple route · Autos & taxis available" },
    ],
    food: [
      { emoji: "🍚", name: "Thanjavur Grand Sappadu", desc: "Royal banana-leaf feast — 12+ preparations" },
      { emoji: "🥮", name: "Paal Kozhukattai", desc: "Rice dumplings in cardamom coconut milk" },
      { emoji: "🍯", name: "Kavuni Arisi Payasam", desc: "Black rice pudding — Chettiar speciality" },
      { emoji: "🥣", name: "Ven Pongal", desc: "Rice & moong dal with pepper, cumin, ghee" },
      { emoji: "🫙", name: "Manga Pachadi", desc: "Raw mango in jaggery — festival staple, balanced taste" },
      { emoji: "🍱", name: "Kuzhambu Rice", desc: "Tangy tamarind gravy poured over steamed rice" },
    ],
    hotels: [
      { icon: "👑", name: "Ideal River View Resort", detail: "4★ · Palli Agraharam · Cauvery-side property, river views", stars: "★★★★" },
      { icon: "🏨", name: "Hotel Sangam Thanjavur", detail: "4★ · Trichy Rd · Pool, multi-cuisine, conference hall", stars: "★★★★" },
      { icon: "🛎", name: "Gopika Heritage Hotel", detail: "3★ · Near Big Temple · Heritage building, traditional service", stars: "★★★" },
      { icon: "🏩", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Reliable; walking distance to main temple", stars: "★★★" },
      { icon: "🏠", name: "Orchid Inn", detail: "Budget · Central · Clean rooms, popular with pilgrims", stars: "★★" },
    ],
    coords: "10.7870° N, 79.1378° E",
    mapUrl: "https://maps.google.com/?q=Thanjavur,Tamil+Nadu",
  },
  {
    id: "madurai",
    name: "Madurai",
    region: "South Tamil Nadu · Temple City",
    emoji: "⛩️",
    color: "#6B2B00",
    mapX: 190, mapY: 353,
    desc: "One of the oldest continuously inhabited cities on earth — Madurai has flourished for over 2,500 years. Its crown jewel, the Meenakshi Amman Temple, commands the heart of the old city with four towering gopurams covered in thousands of painted sculptures, drawing pilgrims and travellers from every continent. The city never sleeps — the temple corridors pulse 24 hours a day.",
    stats: [
      { value: "2,500+", label: "Years Old" },
      { value: "33,000", label: "Temple Sculptures" },
      { value: "Jasmine", label: "City's Fragrance" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (Chithirai festival in April is extraordinary but hot)" },
      { label: "Known For", value: "Meenakshi Temple · Thirumalai Nayak Palace · Madurai Malli (jasmine) · Jigarthanda" },
      { label: "Festival", value: "Chithirai Festival (April/May) — massive temple car procession through city streets" },
      { label: "Airport", value: "Madurai Airport (IXM) — 12 km from the Meenakshi Temple" },
      { label: "City Life", value: "Madurai market operates 24 hrs — flower sellers, jasmine, turmeric at 3 AM" },
    ],
    travel: [
      { icon: "✈️", name: "By Air", detail: "Flights to Chennai, Mumbai, Bengaluru & Delhi (IndiGo, Air India, SpiceJet)" },
      { icon: "🚂", name: "By Train", detail: "Madurai Junction — Pandian Express from Chennai overnight (8 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "Mattuthavani bus stand — every 30 min from Chennai, Coimbatore, Trichy" },
    ],
    travelExtra: [
      { label: "From Chennai", value: "460 km · 8 hrs by Pandian Express · 9 hrs by bus · 1.5 hrs by flight" },
      { label: "City Transport", value: "Cycle rickshaws in temple area · App cabs · Autos" },
    ],
    food: [
      { emoji: "🐑", name: "Mutton Biryani", desc: "Madurai's signature dum biryani — peppery, fragrant, seeraga samba rice" },
      { emoji: "🧊", name: "Jigarthanda", desc: "Ice cream, sarsaparilla, almond gum & milk — a Madurai invention" },
      { emoji: "🥛", name: "Kari Dosai", desc: "Crispy dosa with spiced minced mutton masala filling" },
      { emoji: "🍢", name: "Kola Urundai", desc: "Spiced minced mutton balls, deep fried — old city street food" },
      { emoji: "🧆", name: "Paruthi Paal", desc: "Cotton-seed milk — a unique Madurai speciality, slightly nutty" },
      { emoji: "🌺", name: "Malli Juice", desc: "Fresh jasmine essence — only in season; incredibly fragrant" },
    ],
    hotels: [
      { icon: "👑", name: "Heritage Madurai", detail: "5★ · Bypass Rd · Colonial club-style resort with large pool", stars: "★★★★★" },
      { icon: "🏨", name: "Taj Gateway Madurai", detail: "4★ · Papakoil St · Panoramic temple views from rooftop", stars: "★★★★" },
      { icon: "🛎", name: "Hotel Sangam", detail: "4★ · Collectorate · Long-established city-centre comfort", stars: "★★★★" },
      { icon: "🏩", name: "Hotel Park Plaza", detail: "3★ · West Veli St · Walking distance from Meenakshi Temple", stars: "★★★" },
      { icon: "🏠", name: "Zostel Madurai", detail: "Budget · Near temple · Backpacker dormitories & private rooms", stars: "★★★" },
    ],
    coords: "9.9252° N, 78.1198° E",
    mapUrl: "https://maps.google.com/?q=Madurai,Tamil+Nadu",
  },
  {
    id: "kodaikanal",
    name: "Kodaikanal",
    region: "Palani Hills · 2,133 m Altitude",
    emoji: "🌸",
    color: "#1A5C3D",
    mapX: 125, mapY: 325,
    desc: "Perched in the Palani Hills at 2,133 m, Kodaikanal is Tamil Nadu's most romantic hill station. The star-shaped Kodaikanal Lake, mist-clad Pillar Rocks rising 122 metres from the forest floor, and the legendary Kurinji flower that blooms only once every 12 years make this a destination of rare natural wonder. Coaker's Walk offers views of the plains 2 km below.",
    stats: [
      { value: "2,133m", label: "Altitude" },
      { value: "Star-shaped", label: "Kodai Lake" },
      { value: "12 years", label: "Kurinji Blooms" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "April – June (summer peak); Sep – Nov (post-monsoon, clear views)" },
      { label: "Known For", value: "Kodaikanal Lake · Pillar Rocks · Bryant Park · Coaker's Walk · Kurinji Flower" },
      { label: "Unique", value: "Star-shaped man-made lake built by British in 1863; bicycle riding around it is iconic" },
      { label: "Kurinji", value: "Strobilanthes kunthianus blooms once in 12 years — entire hillside turns purple" },
      { label: "Airport", value: "Madurai Airport (IXM) — 120 km (2.5 hrs ghat road); Trichy (TRZ) — 180 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train to Base", detail: "Kodai Road station (120 km away) from Chennai (6.5 hrs); then ghat bus" },
      { icon: "🚌", name: "By Bus", detail: "From Madurai (4 hrs ghat), Coimbatore (5 hrs), Chennai overnight (10 hrs)" },
      { icon: "🚗", name: "By Road", detail: "Via Dindigul · Palani; scenic but technical ghat road — 7 hairpin bends" },
    ],
    travelExtra: [
      { label: "From Madurai", value: "120 km · 4 hrs via Alanganallur ghat road" },
      { label: "Local Transport", value: "Bicycle rentals around lake · Autos for viewpoints · Horse riding" },
    ],
    food: [
      { emoji: "🧀", name: "Kodai Cheese", desc: "Home-made mild white cheese — sold at Pastry Corner since 1935" },
      { emoji: "🍫", name: "Homemade Chocolate", desc: "Artisan chocolates in every flavour — a Kodai institution" },
      { emoji: "🥧", name: "Garlic Bread Toast", desc: "A legacy of Silver Oak café in the mist — impossible to resist" },
      { emoji: "🍵", name: "Kodai Coffee", desc: "Fresh-roasted Palani Hill coffee brewed strong" },
      { emoji: "🥩", name: "Mutton Curry", desc: "Mountain mutton in Kodai-spice blend, served with appam" },
      { emoji: "🍓", name: "Strawberry Jam", desc: "Hill-grown strawberry preserves — buy directly from estates" },
    ],
    hotels: [
      { icon: "👑", name: "The Carlton Hotel", detail: "5★ · Lake Rd · Heritage property, lake-facing rooms, pool", stars: "★★★★★" },
      { icon: "🏨", name: "Club Mahindra Kodaikanal", detail: "4★ · Coaker's Walk · Resort with valley views & activities", stars: "★★★★" },
      { icon: "🛎", name: "Sterling Kodai Lake", detail: "4★ · Lake Rd · Lake-facing cottages, bonfire evenings", stars: "★★★★" },
      { icon: "🏩", name: "Villa Retreat", detail: "3★ · Coaker's Walk · Colonial bungalow with period furniture", stars: "★★★" },
      { icon: "🏠", name: "Zostel Kodaikanal", detail: "Budget · Lake area · Sociable hostel with outdoor activities", stars: "★★★" },
    ],
    coords: "10.2381° N, 77.4892° E",
    mapUrl: "https://maps.google.com/?q=Kodaikanal,Tamil+Nadu",
  },
  {
    id: "rameswaram",
    name: "Rameswaram",
    region: "Ramanathapuram · Island Pilgrim Town",
    emoji: "🕌",
    color: "#1A3A5C",
    mapX: 315, mapY: 418,
    isIsland: true,
    desc: "Rameswaram sits on Pamban Island, connected to the mainland by the stunning Pamban Bridge over the Palk Strait. The Ramanathaswamy Temple's pillared corridor — 1,212 metres long — is among the longest in the world. Hindus believe bathing at its 22 theerthams (sacred wells) washes away all sins, making this one of the holiest places on earth.",
    stats: [
      { value: "1,212m", label: "Temple Corridor" },
      { value: "22", label: "Sacred Wells" },
      { value: "Pamban", label: "Sea Bridge" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – April (calm sea; avoid June–September cyclone season)" },
      { label: "Known For", value: "Ramanathaswamy Temple · Pamban Bridge · Dhanushkodi Ghost Town · APJ Abdul Kalam Memorial" },
      { label: "Significance", value: "One of Hinduism's Char Dham — the four supreme pilgrimage destinations" },
      { label: "Dhanushkodi", value: "Ruined town at India's tip — destroyed by 1964 cyclone; now a ghost town" },
      { label: "Airport", value: "Madurai Airport (IXM) — 165 km · 3 hrs by road" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Rameswaram station — Sethu Express from Chennai (15 hrs overnight)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Madurai (3.5 hrs) and direct from Chennai (12 hrs overnight)" },
      { icon: "🌊", name: "Pamban Bridge", detail: "A rail & road bridge crossing the Palk Strait — dramatic approach to island" },
    ],
    travelExtra: [
      { label: "From Madurai", value: "165 km · 3.5 hrs by road or 3 hrs by Rameswaram–Madurai Express" },
      { label: "Local Transport", value: "Cycle rickshaws in temple area · Jeep to Dhanushkodi (16 km)" },
    ],
    food: [
      { emoji: "🦐", name: "Prawn Curry", desc: "Palk Strait prawns in coconut & red chilli gravy" },
      { emoji: "🐠", name: "Fish Biryani", desc: "Local catch dum-cooked with saffron & Chettinad spices" },
      { emoji: "🥥", name: "Coconut Chutney", desc: "Fresh-ground with curry leaves, mustard & green chilli" },
      { emoji: "🍵", name: "Ragi Koozh", desc: "Fermented millet porridge — the classic pilgrim fuel" },
      { emoji: "🥜", name: "Peanut Sundal", desc: "Steamed peanuts tossed with coconut & mustard" },
      { emoji: "🍌", name: "Banana Chips", desc: "Island-style thin-sliced fried in pure coconut oil" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Daiwik", detail: "4★ · West Car St · Pilgrimage-oriented luxury hotel", stars: "★★★★" },
      { icon: "🛎", name: "Hymas Beach Resort", detail: "3★ · Sea-facing · Beach cottages with ocean view", stars: "★★★" },
      { icon: "🏩", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Sea-facing rooms at reasonable rates", stars: "★★★" },
      { icon: "🏠", name: "Sri Saradha Lodge", detail: "Budget · Near temple · Simple clean rooms for pilgrims", stars: "★★" },
      { icon: "🕌", name: "Mathura Hotel", detail: "Budget · North Car St · Walking distance to all sacred theerthams", stars: "★★" },
    ],
    coords: "9.2876° N, 79.3129° E",
    mapUrl: "https://maps.google.com/?q=Rameswaram,Tamil+Nadu",
  },
  {
    id: "tuticorin",
    name: "Tuticorin",
    region: "Gulf of Mannar · Pearl City",
    emoji: "🦪",
    color: "#1A4A5C",
    mapX: 175, mapY: 460,
    desc: "Thoothukudi — Tuticorin — is Tamil Nadu's second major port, historically the world's greatest pearl fishing centre. Marco Polo described its pearl trade in the 13th century. Today it is the gateway to the Gulf of Mannar Marine National Park — one of India's most biodiverse marine ecosystems — and home to the legendary Tuticorin salt flats that turn flamingo-pink.",
    stats: [
      { value: "2nd", label: "TN's Largest Port" },
      { value: "Gulf of Mannar", label: "Marine Park" },
      { value: "Pearls", label: "Historical Trade" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (calm Gulf of Mannar; dolphins active)" },
      { label: "Known For", value: "Gulf of Mannar Marine Park · Salt pans · Pearl history · Hare Island · Surfing" },
      { label: "Marine Life", value: "Dugong, sea turtle, seahorse, 3,600 species — India's most biodiverse marine park" },
      { label: "Salt Flats", value: "Pink salt flats near town — flamingos visit November–February" },
      { label: "Airport", value: "Tuticorin Airport (TCR) — 17 km from city centre; flights to Chennai" },
    ],
    travel: [
      { icon: "✈️", name: "By Air", detail: "Tuticorin Airport (TCR) — daily flights to Chennai; connect onward" },
      { icon: "🚂", name: "By Train", detail: "Tuticorin station — trains from Chennai (10 hrs), Madurai (3 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Madurai (3 hrs), Tirunelveli (1 hr), Chennai (12 hrs)" },
    ],
    travelExtra: [
      { label: "From Madurai", value: "160 km · 3 hrs by road or bus" },
      { label: "Marine Park Access", value: "Boat rides from Tuticorin harbour to Hare Island & Van Island" },
    ],
    food: [
      { emoji: "🦞", name: "Lobster Masala", desc: "Gulf of Mannar lobster in coconut-tomato gravy" },
      { emoji: "🦑", name: "Squid Fry", desc: "Deep-sea squid — crispy fried with chilli & fennel seeds" },
      { emoji: "🐟", name: "Sura Puttu", desc: "Shredded shark meat stir-fried with onion & spices" },
      { emoji: "🥥", name: "Korva Kari", desc: "Dried fish curry cooked in coconut milk" },
      { emoji: "🍚", name: "Pacha Kari Sadam", desc: "Mixed vegetable rice cooked in banana leaf" },
      { emoji: "🫙", name: "Karuvaeppilai Sadam", desc: "Curry leaf rice — fragrant, simple, coastal soul food" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Anandha Inn", detail: "3★ · Bryant Nagar · Pool, restaurant, comfortable rooms", stars: "★★★" },
      { icon: "🛎", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Sea-facing, reliable value", stars: "★★★" },
      { icon: "🏩", name: "Hotel Vasantha Bhavan", detail: "2★ · Central · Near port & railway, clean budget rooms", stars: "★★" },
      { icon: "🏠", name: "Sree Guest House", detail: "Budget · Port area · For early ferry departures", stars: "★★" },
      { icon: "🌊", name: "Marine Eco-Stay", detail: "Beach homestay · Tharuvaikulam village · Fishing community experience", stars: "★★★" },
    ],
    coords: "8.7642° N, 78.1348° E",
    mapUrl: "https://maps.google.com/?q=Thoothukudi,Tamil+Nadu",
  },
  {
    id: "tirunelveli",
    name: "Tirunelveli",
    region: "Deep South Tamil Nadu · Halwa City",
    emoji: "🍮",
    color: "#5C3A1A",
    mapX: 138, mapY: 467,
    desc: "Tirunelveli sits at the confluence of rivers Thamirabarani and Chittar — one of Tamil Nadu's oldest living cities. It is famous nationally for Tirunelveli Halwa — a dense, translucent wheat-based confection made only with Thamirabarani river water, claimed by locals to be irreproducible elsewhere. The nearby Papanasam waterfalls and Courtallam (the Spa of South India) are within easy reach.",
    stats: [
      { value: "Thamirabarani", label: "Sacred River" },
      { value: "Courtallam", label: "Spa of S.India" },
      { value: "Halwa", label: "National Famous Dish" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March; Courtallam best July–September (post-monsoon falls)" },
      { label: "Known For", value: "Tirunelveli Halwa · Nellaiappar Temple · Courtallam Falls · Papanasam · Manimuthar Dam" },
      { label: "Halwa", value: "Made only with Thamirabarani water and pure wheat starch; locals claim taste changes 1 km away" },
      { label: "Courtallam", value: "Nine waterfalls at 160m — Ayurvedic properties in the water; 65 km from city" },
      { label: "Airport", value: "Madurai Airport (IXM) — 150 km; Tuticorin Airport (TCR) — 60 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Tirunelveli Junction — trains from Chennai (12 hrs), Madurai (2 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Madurai (2 hrs), Kanyakumari (2 hrs), Chennai (14 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-744 from Madurai (165 km · 2.5 hrs); NH-44 to Kanyakumari (80 km)" },
    ],
    travelExtra: [
      { label: "From Kanyakumari", value: "80 km · 1.5 hrs — most visitors combine the two" },
      { label: "To Courtallam Falls", value: "65 km from Tirunelveli · 1.5 hrs; popular Jul–Sep waterfall season" },
    ],
    food: [
      { emoji: "🍮", name: "Tirunelveli Wheat Halwa", desc: "Dense translucent sweet — cook in Thamirabarani water. Buy at Iruttu Kadai (dark shop)" },
      { emoji: "🥞", name: "Kadalai Maavu Dosa", desc: "Chickpea flour dosa with coconut & onion filling" },
      { emoji: "🍛", name: "Mutton Kuzhambu", desc: "Deep south peppery mutton curry in sesame oil" },
      { emoji: "🥣", name: "Koozh", desc: "Fermented millet porridge — labourers' breakfast, surprisingly delicious" },
      { emoji: "🌶", name: "Nellai Chicken Fry", desc: "Dry-fried chicken with Nellai's signature pepper-heavy masala" },
      { emoji: "🍌", name: "Pachai Vazhai Pazham", desc: "Raw banana curry with freshly grated coconut" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Aryaas", detail: "3★ · Main Rd · Vegetarian luxury hotel, pure south TN cuisine", stars: "★★★" },
      { icon: "🛎", name: "Hotel Bharani", detail: "3★ · Junction area · Central, clean, reliable family hotel", stars: "★★★" },
      { icon: "🏩", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Near bus stand, reliable service", stars: "★★" },
      { icon: "🏠", name: "Hotel Periyas Grand", detail: "Budget · Railway Station Rd · Neat, popular with traders", stars: "★★" },
      { icon: "🌊", name: "Courtallam Falls Resort", detail: "3★ · Near falls · Seasonal (Jul–Sep); experience waterfall in room balcony", stars: "★★★" },
    ],
    coords: "8.7139° N, 77.7567° E",
    mapUrl: "https://maps.google.com/?q=Tirunelveli,Tamil+Nadu",
  },
  {
    id: "kanyakumari",
    name: "Kanyakumari",
    region: "The Southern Tip · Where 3 Oceans Meet",
    emoji: "🌅",
    color: "#0D3B5C",
    mapX: 126, mapY: 527,
    desc: "Kanyakumari is as far south as India goes. Standing here, you watch the Arabian Sea to your west, the Bay of Bengal to the east, and the Indian Ocean ahead — a trifecta of waters meeting at Land's End. On full-moon nights the moon rises exactly where the sun set; at equinox the sun rises and sets as a disc over the sea on the same day.",
    stats: [
      { value: "3", label: "Oceans Meet" },
      { value: "Sunrise", label: "Over the Sea" },
      { value: "133 ft", label: "Thiruvalluvar Statue" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March; sunrise on the sea best mid-November" },
      { label: "Known For", value: "Vivekananda Rock Memorial · Thiruvalluvar Statue · Kumari Amman Temple · Sunset Point" },
      { label: "Special", value: "Full moon October: moon rises as sun sets — both visible simultaneously" },
      { label: "Distance", value: "87 km from Trivandrum · 253 km from Madurai · 700 km from Chennai" },
      { label: "Airport", value: "Trivandrum International Airport (TRV) — 87 km (1.5 hrs)" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Kanyakumari station — Himsagar Express from Delhi; Cape Express from Chennai (15 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Trivandrum (1.5 hrs), Madurai (4.5 hrs), Chennai (14 hrs overnight)" },
      { icon: "✈️", name: "By Air", detail: "Trivandrum Airport (TRV) — 87 km · 1.5 hrs by road or direct bus" },
    ],
    travelExtra: [
      { label: "From Trivandrum", value: "87 km · 1.5 hrs by bus · 1.5 hrs by train — most popular access route" },
      { label: "Local Transport", value: "Ferry to Vivekananda Rock (₹34) · Walking promenade · Autos" },
    ],
    food: [
      { emoji: "🐡", name: "Kothamalli Fish Curry", desc: "Coriander-base coastal fish curry — Land's End style" },
      { emoji: "🥞", name: "Neer Dosa", desc: "Paper-thin delicate rice crêpe with coconut chutney" },
      { emoji: "🦑", name: "Squid Masala", desc: "Deep-sea squid in Kanyakumari's three-ocean spice blend" },
      { emoji: "🫙", name: "Nannari Sarbath", desc: "Indian sarsaparilla sherbet — cooling & intensely aromatic" },
      { emoji: "🍵", name: "Kerala Tea", desc: "Full-bodied orthodox black tea from the neighbouring hills" },
      { emoji: "🍌", name: "Elaneer Payasam", desc: "Tender coconut pudding with palm jaggery & cardamom" },
    ],
    hotels: [
      { icon: "👑", name: "Sparsa Resort", detail: "4★ · Sea Rd · Sunrise sea-view from every room, infinity pool", stars: "★★★★" },
      { icon: "🏨", name: "Hotel Samudera (TTDC)", detail: "3★ · Sea Rd · Govt heritage building, ocean views, reliable", stars: "★★★" },
      { icon: "🛎", name: "Hotel Maadhini", detail: "3★ · Main Rd · Rooftop restaurant facing the southern tip", stars: "★★★" },
      { icon: "🏩", name: "Hotel Seaview", detail: "2★ · Budget · Right on the ocean promenade", stars: "★★" },
      { icon: "🏠", name: "Lakshmi Tourist Home", detail: "Budget · Near temple · Pilgrim-friendly guesthouse", stars: "★★" },
    ],
    coords: "8.0883° N, 77.5385° E",
    mapUrl: "https://maps.google.com/?q=Kanyakumari,Tamil+Nadu",
  },
  {
    id: "dindigul",
    name: "Dindigul",
    region: "Central Tamil Nadu · Lock & Biryani City",
    emoji: "🔒",
    color: "#7C3D00",
    mapX: 183, mapY: 315,
    desc: "Dindigul is celebrated for two things it does better than anywhere else in India: hand-crafted steel locks that once secured the Nawabs' treasuries, and the Dindigul Thalappakatti Biryani — a seeraga samba rice dum-biryani so beloved that restaurants bearing its name have spread across the world. Perched above the town, a 3rd-century rock fort offers commanding views of the plains and Sirumalai Hills.",
    stats: [
      { value: "300 yrs", label: "Lock Making" },
      { value: "Thalappakatti", label: "World-Famous Biryani" },
      { value: "Rock Fort", label: "3rd Century" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (pleasant, dry)" },
      { label: "Known For", value: "Dindigul Lock · Thalappakatti Biryani · Dindigul Rock Fort · Sirumalai Hills" },
      { label: "Locks", value: "GI-tagged Dindigul locks — made by hand with no two quite alike; sold at Palani Rd market" },
      { label: "Sirumalai", value: "A small isolated hill range 20 km east — coffee estates, homestays & bird watching" },
      { label: "Airport", value: "Madurai Airport (IXM) — 66 km south; Trichy (TRZ) — 100 km north" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Dindigul Junction — trains from Chennai (7 hrs), Madurai (1.5 hrs), Coimbatore (3 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Madurai (1.5 hrs), Trichy (2 hrs), Coimbatore (3 hrs), Chennai (8 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-44 from Madurai (66 km · 1.5 hrs); NH-44 from Trichy (100 km · 2 hrs)" },
    ],
    travelExtra: [
      { label: "From Madurai", value: "66 km · 1.5 hrs — easy same-day trip or stopover" },
      { label: "From Kodaikanal", value: "Kodaikanal base: Kodai Road station 30 km from Dindigul; connect by road" },
    ],
    food: [
      { emoji: "🍗", name: "Thalappakatti Biryani", desc: "The original — seeraga samba rice, mutton or chicken, served with raita & gravy" },
      { emoji: "🥩", name: "Mutton Varuval", desc: "Dry-fried mutton with Dindigul pepper & fennel masala" },
      { emoji: "🥞", name: "Kothu Parotta", desc: "Shredded flatbread on cast iron — a late-night staple" },
      { emoji: "🧆", name: "Kola Urundai", desc: "Spiced minced meat balls, fried crisp — with tomato chutney" },
      { emoji: "☕", name: "Filter Coffee", desc: "Roadside kadai coffee — strong, sweet, served in steel tumbler" },
      { emoji: "🥭", name: "Sirumalai Mango", desc: "Hill-grown small mango — intensely fragrant & sweet, seasonal" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Picnic", detail: "3★ · Palani Rd · Reliable, clean, restaurant on-site", stars: "★★★" },
      { icon: "🛎", name: "Hotel Sree Kumaran", detail: "3★ · Junction Rd · Central, popular with business travellers", stars: "★★★" },
      { icon: "🏩", name: "Hotel Aathithya", detail: "2★ · Near bus stand · Budget rooms, decent meals", stars: "★★" },
      { icon: "🏠", name: "Sirumalai Hill Resort", detail: "Eco-resort · Sirumalai Hills · Coffee estate stays, birding", stars: "★★★" },
      { icon: "🌿", name: "Transit Stay", detail: "Most visitors stop for biryani & continue to Kodaikanal or Madurai", stars: "—" },
    ],
    coords: "10.3624° N, 77.9695° E",
    mapUrl: "https://maps.google.com/?q=Dindigul,Tamil+Nadu",
  },
  {
    id: "tirupur",
    name: "Tirupur",
    region: "Western Tamil Nadu · Knitwear Capital",
    emoji: "👕",
    color: "#1A4A6B",
    mapX: 127, mapY: 246,
    desc: "Tirupur is the knitwear and garment export capital of India — a city that supplies T-shirts, sportswear, and hosiery to the world's biggest fashion brands. Despite its industrial identity, Tirupur is flanked by the Nilgiris to the north and is the gateway to Anamalai Tiger Reserve and the tea-and-coffee hills of Valparai. The city's dyeing industry has produced innovations in sustainable textile processing.",
    stats: [
      { value: "90%", label: "India's Knitwear Exports" },
      { value: "₹35,000 Cr", label: "Annual Export Value" },
      { value: "Valparai", label: "Hill Gateway" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – February (cool & dry; Valparai accessible year-round)" },
      { label: "Known For", value: "Knitwear & garment industry · Tirupur Kumaran memorial · Valparai hills · Anamalai Reserve" },
      { label: "Valparai", value: "100 km from Tirupur — tea estates, elephant crossings, Sholayar dam; one of TN's hidden gems" },
      { label: "Anamalai", value: "Anamalai Tiger Reserve (Indira Gandhi WLS) — tigers, elephants, safari from Pollachi" },
      { label: "Airport", value: "Coimbatore International Airport (CBE) — 45 km east" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Tirupur station — on Chennai–Coimbatore main line; frequent express trains" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Coimbatore (45 min), Chennai (8 hrs), Madurai (4 hrs)" },
      { icon: "✈️", name: "Nearest Airport", detail: "Coimbatore Airport (CBE) — 45 km · 1 hr by taxi" },
    ],
    travelExtra: [
      { label: "From Coimbatore", value: "45 km · 45 min by train or road — easiest access point" },
      { label: "To Valparai", value: "100 km from Tirupur via Pollachi · 3.5 hrs (40 hairpin bends!)" },
    ],
    food: [
      { emoji: "🍳", name: "Tirupur Salna Parotta", desc: "Layered parotta with watery salna (gravy) — street staple" },
      { emoji: "☕", name: "Sulaimani Tea", desc: "Black tea with lemon, cloves & cardamom — refreshing" },
      { emoji: "🥘", name: "Chicken Kuzhambu", desc: "Tamarind-coconut chicken curry with rice" },
      { emoji: "🫕", name: "Keerai Masiyal", desc: "Mashed spinach with garlic & mustard tempering" },
      { emoji: "🥞", name: "Appam & Stew", desc: "Fermented bowl-shaped crêpe with vegetable coconut stew" },
      { emoji: "🍫", name: "Valparai Tea Chocolates", desc: "Tea-infused artisan chocolates from Valparai estates" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Selvam Grand", detail: "3★ · Avinashi Rd · Business hotel, restaurant, centrally located", stars: "★★★" },
      { icon: "🛎", name: "Hotel Prince Residency", detail: "3★ · Town centre · Clean rooms, popular with textile buyers", stars: "★★★" },
      { icon: "🏩", name: "Hotel Anand Bhavan", detail: "2★ · Near railway · Budget, clean, good veg restaurant", stars: "★★" },
      { icon: "🌿", name: "Valparai Green Valley Resort", detail: "3★ · Valparai · Tea-estate resort; elephant sightings at dawn", stars: "★★★" },
      { icon: "🌄", name: "Sholayar Estate Bungalow", detail: "Heritage stay · Valparai · Colonial planter's bungalow; advance booking", stars: "★★★★" },
    ],
    coords: "11.1085° N, 77.3411° E",
    mapUrl: "https://maps.google.com/?q=Tirupur,Tamil+Nadu",
  },
  {
    id: "namakkal",
    name: "Namakkal",
    region: "Central Tamil Nadu · Lorry & Egg Capital",
    emoji: "🚛",
    color: "#4A3D00",
    mapX: 201, mapY: 235,
    desc: "Namakkal is one of India's most surprising cities — it dominates two entirely unrelated industries: lorry body-building (over 60% of India's truck bodies are fabricated here) and poultry farming (India's egg capital, producing 10 crore eggs daily). Above the town rises the Namakkal Rock Fort with the ancient Narasimha temple carved into a cliff, and the Anjaneyar temple housing India's largest monolithic Hanuman statue.",
    stats: [
      { value: "60%", label: "India's Truck Bodies" },
      { value: "10 Cr", label: "Eggs Daily" },
      { value: "Narasimha", label: "Rock Fort Temple" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (pleasant; Namakkal Rock Fort ideal in winter morning)" },
      { label: "Known For", value: "Namakkal Fort · Narasimha Temple · Anjaneyar Temple · Lorry body industry · Poultry" },
      { label: "Anjaneyar Temple", value: "Houses India's largest monolithic Hanuman idol — 18 feet tall, carved from single rock" },
      { label: "Industry", value: "Visit the lorry body workshop clusters on NH-544 — a unique industrial spectacle" },
      { label: "Airport", value: "Salem Airport (small domestic airstrip) — 40 km; Trichy (TRZ) — 120 km" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Nearest major station: Salem Jn (40 km) — then bus or taxi to Namakkal" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Salem (40 km · 1 hr), Trichy (120 km · 2.5 hrs), Coimbatore (100 km · 2 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-544 from Salem (40 km · 45 min); NH-544 from Coimbatore (100 km · 2 hrs)" },
    ],
    travelExtra: [
      { label: "From Salem", value: "40 km · 45 min — best access point; many visitors combine both" },
      { label: "From Trichy", value: "120 km · 2.5 hrs by road via Karur" },
    ],
    food: [
      { emoji: "🥚", name: "Egg Biryani", desc: "Egg capital's specialty — perfectly boiled eggs in seeraga samba dum biryani" },
      { emoji: "🍳", name: "Country Egg Omelette", desc: "Fresh farm-egg omelette with green chilli & onion — roadside staple" },
      { emoji: "🥘", name: "Nattu Kozhi Curry", desc: "Country chicken (slow-growing) in black pepper kuzhambu" },
      { emoji: "🍚", name: "Sambar Sadam", desc: "Hotel-style sambar rice with ghee & pappadam" },
      { emoji: "☕", name: "Filter Kaapi", desc: "Strong filter coffee — Salem-belt style, very rich" },
      { emoji: "🥣", name: "Kanji & Pickle", desc: "Rice porridge with mango pickle — traditional breakfast" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Vijay Park", detail: "3★ · Tiruchengode Rd · Clean, central, reliable restaurant", stars: "★★★" },
      { icon: "🛎", name: "Hotel Nandha", detail: "2★ · Bus Stand Rd · Budget, good location near fort", stars: "★★" },
      { icon: "🏩", name: "Hotel Salem Royal", detail: "Stay in Salem (40 km) · Better facilities · Day trip to Namakkal", stars: "★★★" },
      { icon: "🏠", name: "Namakkal Circuit House", detail: "Govt · Budget · Book through District Collectorate", stars: "★★" },
      { icon: "🌿", name: "Day-Trip Option", detail: "Most visitors stay in Salem & visit Namakkal as a half-day excursion", stars: "—" },
    ],
    coords: "11.2189° N, 78.1673° E",
    mapUrl: "https://maps.google.com/?q=Namakkal,Tamil+Nadu",
  },
  {
    id: "erode",
    name: "Erode",
    region: "Western Tamil Nadu · Turmeric City",
    emoji: "🌿",
    color: "#5C4A00",
    mapX: 161, mapY: 224,
    desc: "Erode is Tamil Nadu's turmeric capital — the world's largest turmeric trading market operates here, turning the city golden-yellow during trading season. Known as 'Manjal Nagaram' (Turmeric Town), Erode is also a major centre for the handloom weaving of kora muslin and cotton textiles. The Periyar River flows through the city, and Bhavani Sagar dam — one of the largest in Tamil Nadu — lies just 36 km away.",
    stats: [
      { value: "World's Largest", label: "Turmeric Market" },
      { value: "Periyar", label: "River City" },
      { value: "Kora Muslin", label: "Handloom Heritage" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March; turmeric harvest season (Jan–March) is special" },
      { label: "Known For", value: "Turmeric Market · Bhavani Sagar Dam · Periyar River · Handloom textiles · Sangameswarar Temple" },
      { label: "Turmeric Market", value: "Visit the Erode Turmeric Merchant Association market early morning — a sea of golden yellow" },
      { label: "Bhavani Sagar", value: "One of TN's biggest dams with a large reservoir — boating & picnic; 36 km from Erode" },
      { label: "Airport", value: "Coimbatore International Airport (CBE) — 80 km west" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Erode Junction — major rail junction; trains from Chennai (6 hrs), Coimbatore (1.5 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Coimbatore (1.5 hrs), Salem (1.5 hrs), Chennai (7 hrs), Madurai (4 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-544 from Coimbatore (80 km); NH-81 from Salem (60 km · 1.5 hrs)" },
    ],
    travelExtra: [
      { label: "From Coimbatore", value: "80 km · 1.5 hrs — very well connected by train & road" },
      { label: "From Salem", value: "60 km · 1.5 hrs — Salem–Erode corridor is highly connected" },
    ],
    food: [
      { emoji: "🌿", name: "Turmeric Milk", desc: "Fresh-pressed turmeric in warm milk — sold at market stalls during harvest" },
      { emoji: "🍚", name: "Erode Tiffin Meal", desc: "Pongal, idli, dosa with hotel sambar — Periyar-belt breakfast style" },
      { emoji: "🐑", name: "Mutton Biryani", desc: "Erode-style biryani with jeerakasala rice, cooked in river clay pots" },
      { emoji: "🥞", name: "Nei Roast Dosa", desc: "Ghee-roasted golden dosa with onion-tomato chutney" },
      { emoji: "🍋", name: "Bhavani Kanji", desc: "Fermented rice porridge with pickle — dam-side restaurant staple" },
      { emoji: "☕", name: "Jaggery Coffee", desc: "Filter coffee sweetened with Erode's own palm jaggery" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel KVR Grand", detail: "3★ · Brough Rd · Pool, restaurant, most modern hotel in Erode", stars: "★★★" },
      { icon: "🛎", name: "Hotel Ariyanayaki", detail: "3★ · Perundurai Rd · Clean, business-friendly, near market", stars: "★★★" },
      { icon: "🏩", name: "Hotel Sree Annapoorna", detail: "2★ · Junction area · Pure vegetarian hotel, famous for meals", stars: "★★" },
      { icon: "🏠", name: "Hotel Tamil Nadu (TTDC)", detail: "Govt · Budget · Near bus stand, functional and reliable", stars: "★★" },
      { icon: "🌊", name: "Bhavani Sagar Resort", detail: "Eco-stay · Dam-side · Simple cottages, boating, birdwatching", stars: "★★★" },
    ],
    coords: "11.3410° N, 77.7172° E",
    mapUrl: "https://maps.google.com/?q=Erode,Tamil+Nadu",
  },
  {
    id: "karur",
    name: "Karur",
    region: "Central Tamil Nadu · Textile Furnishing City",
    emoji: "🪡",
    color: "#3D1A5C",
    mapX: 193, mapY: 259,
    desc: "Karur is the undisputed global capital of home textile furnishings — bed covers, table cloths, kitchen linen, and curtains made here reach department stores across Europe and America. The city sits where the Amaravathi river meets the Cauvery, making it a fertile river-delta town with ancient roots. The Kalyana Pasupatheswarar Temple and Karur's unique lock-step weaving tradition are centuries old.",
    stats: [
      { value: "70%", label: "India's Home Furnishing Exports" },
      { value: "Cauvery", label: "River Confluence" },
      { value: "2,000+", label: "Loom Units" },
    ],
    overview: [
      { label: "Best Time to Visit", value: "October – March (cool & dry; textiles market most active)" },
      { label: "Known For", value: "Handloom exports · Kalyana Pasupatheswarar Temple · Karur deer park · Amaravathi reservoir" },
      { label: "Textiles", value: "Visit the wholesale textile market on Jawahar Bazaar — colourful, vibrant, world-class" },
      { label: "Amaravathi", value: "Amaravathi Dam reservoir, 30 km north — picnic spot with crocodile sanctuary" },
      { label: "Airport", value: "Trichy Airport (TRZ) — 80 km east; Coimbatore (CBE) — 120 km west" },
    ],
    travel: [
      { icon: "🚂", name: "By Train", detail: "Karur station — trains from Chennai (6 hrs), Trichy (1.5 hrs), Coimbatore (2 hrs)" },
      { icon: "🚌", name: "By Bus", detail: "TNSTC from Trichy (1.5 hrs), Coimbatore (2 hrs), Salem (2 hrs), Chennai (6.5 hrs)" },
      { icon: "🚗", name: "By Road", detail: "NH-44 from Trichy (80 km · 1.5 hrs); NH-44 from Coimbatore (120 km · 2 hrs)" },
    ],
    travelExtra: [
      { label: "From Trichy", value: "80 km · 1.5 hrs — popular combination for a day trip" },
      { label: "From Coimbatore", value: "120 km · 2 hrs via NH-544 to Erode then NH-81" },
    ],
    food: [
      { emoji: "🍱", name: "Karur Hotel Meals", desc: "Traditional Cauvery delta banana-leaf meal — rich, generous servings" },
      { emoji: "🥞", name: "Kal Dosa", desc: "Stone-pan dosa — thick, soft-centred, crisp-edged, served with sambar" },
      { emoji: "🐟", name: "Cauvery Fish Fry", desc: "Fresh Cauvery river catfish fried with ginger-garlic paste" },
      { emoji: "🥣", name: "Kanjipuram Idli", desc: "Spiced temple-style idli with pepper & cumin in the batter" },
      { emoji: "🍮", name: "Aadi Koozh", desc: "Millet porridge with buttermilk & onion — rural summer staple" },
      { emoji: "☕", name: "Kadai Coffee", desc: "Street-side boiled coffee in an iron kadai — intensely strong" },
    ],
    hotels: [
      { icon: "🏨", name: "Hotel Abi Grand", detail: "3★ · Jawahar Bazaar area · Business hotel near textile market", stars: "★★★" },
      { icon: "🛎", name: "Hotel Tamilnadu (TTDC)", detail: "Govt · Budget · Near bus stand, clean & reliable", stars: "★★" },
      { icon: "🏩", name: "Hotel Kaasi", detail: "2★ · Municipal Rd · Central location, budget-friendly", stars: "★★" },
      { icon: "🏠", name: "Amaravathi Resort", detail: "Eco · Near dam · Simple cottages, boat rides, birding", stars: "★★★" },
      { icon: "🌿", name: "Day-Trip Option", detail: "Most textile buyers stay in Trichy (80 km) or Coimbatore (120 km)", stars: "—" },
    ],
    coords: "10.9601° N, 78.0766° E",
    mapUrl: "https://maps.google.com/?q=Karur,Tamil+Nadu",
  },
];
